# Generated by Django 2.2.1 on 2021-09-14 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0002_reloj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('minimo', models.BooleanField()),
                ('estado', models.BooleanField()),
                ('puesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Puesto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='puesto',
            name='user',
            field=models.ManyToManyField(through='planilla.Detalle_puesto', to=settings.AUTH_USER_MODEL),
        ),
    ]
