# Generated by Django 2.2.1 on 2021-09-15 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0003_auto_20210914_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bases_ley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonificacion_incentivo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=7)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mora', models.DecimalField(decimal_places=2, max_digits=9)),
                ('max_pagos', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('no_pagos', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Interes')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=60)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago_movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estado', models.BooleanField()),
                ('movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Tipo_movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentivo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aplica_hora_extra', models.BooleanField()),
                ('cantidad_horas_aut', models.IntegerField()),
                ('valor_horas_extra', models.DecimalField(decimal_places=2, max_digits=3)),
                ('planilla', models.BooleanField()),
                ('honorarios', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_ordinario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dias_trabajados', models.DecimalField(decimal_places=2, max_digits=4)),
                ('incentivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productividad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bases_ley', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Bases_ley')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bases_ley', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Bases_ley')),
                ('impuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Impuesto')),
            ],
        ),
        migrations.AddField(
            model_name='bases_ley',
            name='impuesto',
            field=models.ManyToManyField(through='planilla.Detalle_impuesto', to='planilla.Impuesto'),
        ),
    ]
