# Generated by Django 2.2.1 on 2021-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_auto_20210915_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='interes',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_movimiento',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
    ]
