# Generated by Django 2.2.1 on 2021-09-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_auto_20210916_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_puesto',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
