# Generated by Django 2.2.1 on 2021-09-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0006_auto_20210920_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_puesto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
