# Generated by Django 2.2.1 on 2021-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0008_auto_20210921_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fin_mes',
            field=models.BooleanField(default=False),
        ),
    ]
