# Generated by Django 2.2.1 on 2021-09-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0009_movimiento_fin_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='no_pagos',
        ),
    ]
