# Generated by Django 2.2.1 on 2021-09-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0010_remove_movimiento_no_pagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago_movimiento',
            name='movimiento',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Pago_movimiento',
        ),
    ]
