# Generated by Django 2.2.1 on 2021-09-22 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0011_auto_20210922_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_creacion', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('no_pagos', models.IntegerField()),
                ('fin_mes', models.BooleanField(default=False)),
                ('interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Interes')),
                ('tipo_movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Tipo_movimiento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago_movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estado', models.BooleanField()),
                ('movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Movimiento')),
            ],
        ),
    ]
