# Generated by Django 2.2.1 on 2021-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0012_movimiento_pago_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='monto_salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
