# Generated by Django 2.2.1 on 2021-09-24 18:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0014_auto_20210923_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_puesto',
            name='monto_salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monto_salario'),
        ),
    ]
