# Generated by Django 2.2.1 on 2021-09-27 14:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0015_auto_20210924_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_puesto',
            name='monto_salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto_salario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='porcentaje'),
        ),
    ]
