# Generated by Django 2.2.1 on 2021-09-27 14:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0016_auto_20210927_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto_minimo'),
        ),
    ]
