# Generated by Django 2.2.1 on 2021-09-27 18:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0018_auto_20210927_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='valor_horas_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monto_salario'),
        ),
    ]
