# Generated by Django 2.2.1 on 2021-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0019_auto_20210927_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_planilla',
            name='bonificaciones',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='detalle_planilla',
            name='cuotaIgss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_planilla',
            name='descuentoIsr',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='detalle_planilla',
            name='liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_planilla',
            name='devengadoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_planilla',
            name='totalDeducciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle_planilla',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_planilla',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detalle_planilla',
            name='productividad',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
