# Generated by Django 2.2.1 on 2021-10-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0020_auto_20210930_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_planilla',
        ),
    ]
