# Generated by Django 2.2.1 on 2021-10-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0022_detalle_planilla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_planilla',
        ),
    ]
