# Generated by Django 2.2.1 on 2021-10-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0025_auto_20211001_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_planilla',
        ),
    ]
