# Generated by Django 2.2.1 on 2021-10-01 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0026_delete_detalle_planilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_ordinario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dias_trabajados', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('incentivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonificaciones', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('productividad', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salarioTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuotaIgss', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuentoIsr', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('totalDeducciones', models.DecimalField(decimal_places=2, max_digits=8)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaCreacion', models.DateField()),
                ('bases_ley', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.Bases_ley')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
