# Generated by Django 2.2.1 on 2021-10-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0027_detalle_planilla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_planilla',
        ),
    ]
