# Generated by Django 2.2.1 on 2021-10-12 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0031_detalle_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_puesto',
            name='monto_salario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto_salario'),
        ),
    ]
