# Generated by Django 2.2.1 on 2021-10-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0034_auto_20211012_0645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
