# Generated by Django 2.2.1 on 2021-10-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0036_ingreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
